// Payment Page Constants (using pixels)
export const PAYMENT_CONSTANTS = {
  // Container
  CONTAINER_PADDING: '20px 120px',
  CONTAINER_GAP: '12px',

  // Title
  TITLE_FONT_WEIGHT: 700,
  TITLE_FONT_SIZE: '32px',
  TITLE_LINE_HEIGHT: '40px',
  TITLE_LETTER_SPACING: '-0.32px',
  TITLE_GRADIENT: 'linear-gradient(180deg, #000000 0%, #001354 100%)',
  TITLE_MARGIN_BOTTOM: '8px',

  // Subtitle
  SUBTITLE_FONT_WEIGHT: 400,
  SUBTITLE_FONT_SIZE: '16px',
  SUBTITLE_LINE_HEIGHT: '24px',
  SUBTITLE_LETTER_SPACING: '-0.4px',
  SUBTITLE_COLOR: '#010D3E',
  SUBTITLE_MAX_WIDTH: '535px',
  SUBTITLE_MARGIN_BOTTOM: '20px',

  // Card
  CARD_WIDTH: '620px',
  CARD_MIN_HEIGHT: '450px',
  CARD_BACKGROUND_COLOR: '#FFFFFF',
  CARD_BORDER_RADIUS: '24px',
  CARD_BORDER: '1px solid #EFF0F6',
  CARD_PADDING: '20px 40px',
  CARD_GAP: '20px',
  CARD_BOX_SHADOW: '0px 2px 12px 0px rgba(20, 20, 43, 0.08)',

  // Section
  SECTION_GAP: '12px',
  SECTION_HEADING_FONT_WEIGHT: 500,
  SECTION_HEADING_FONT_SIZE: '16px',
  SECTION_HEADING_LINE_HEIGHT: '16px',
  SECTION_HEADING_COLOR: '#333333',
  SECTION_HEADING_MARGIN_BOTTOM: '12px',

  // Label
  LABEL_FONT_WEIGHT: 500,
  LABEL_FONT_SIZE: '14px',
  LABEL_LINE_HEIGHT: '20px',
  LABEL_COLOR: '#666666',
  LABEL_MARGIN_BOTTOM: '8px',

  // Input
  INPUT_HEIGHT: '44px',
  INPUT_BORDER_RADIUS: '8px',
  INPUT_BACKGROUND_COLOR: '#FFFFFF',
  INPUT_BORDER_COLOR: '#E7EAEB',
  INPUT_BORDER_WIDTH: '1px',
  INPUT_FONT_SIZE: '14px',
  INPUT_LINE_HEIGHT: '20px',
  INPUT_TEXT_COLOR: '#333333',

  // Card Number
  CARD_NUMBER_MARGIN_BOTTOM: '12px',
  CARD_ICONS_GAP: '3px',
  CARD_ICONS_HEIGHT: '16px',

  // Expiry and CVC
  EXPIRY_CVC_GAP: '0',

  // Button
  BUTTON_HEIGHT: '48px',
  BUTTON_BORDER_RADIUS: '8px',
  BUTTON_BACKGROUND_COLOR: '#006045',
  BUTTON_HOVER_BACKGROUND_COLOR: '#004d35',
  BUTTON_TEXT_COLOR: '#FFFFFF',
  BUTTON_FONT_WEIGHT: 500,
  BUTTON_FONT_SIZE: '16px',
  BUTTON_LINE_HEIGHT: '24px',
  BUTTON_MARGIN_TOP: '10px',
} as const;
