// AuthLeftSide Component Constants (using pixels)
export const AUTH_LEFT_CONSTANTS = {
  CONTAINER_WIDTH: '550px',
  CONTAINER_MIN_HEIGHT: '600px',
  CONTAINER_PADDING: '40px 40px',
  CONTAINER_BORDER_RADIUS: '20px',
  BOTTOM_SECTION_GAP: '18px',
  PAGINATION_GAP: '8px',
  PAGINATION_MARGIN_TOP: '20px',
  ACTIVE_INDICATOR_WIDTH: '24px',
  ACTIVE_INDICATOR_HEIGHT: '8px',
  ACTIVE_INDICATOR_BORDER_RADIUS: '10px',
  INACTIVE_INDICATOR_SIZE: '8px',
  INACTIVE_INDICATOR_COLOR: '#81FDCA',
  TEXT_COLOR: '#FFFFFF',
} as const;

