// Navbar Component Constants (using px)
export const NAVBAR_CONSTANTS = {
  HEIGHT: '68px',
  PADDING: '0 24px',
  BACKGROUND_COLOR: '#FFFFFF',
  BOX_SHADOW: '0px 2px 6.4px 0px rgba(161, 161, 161, 0.15)',
  NAV_ITEM_GAP: '40px',
  NAV_FONT_FAMILY: 'Inter, sans-serif',
  NAV_FONT_SIZE: '14px',
  NAV_LINE_HEIGHT: '24px',
  NAV_LETTER_SPACING: '0.14px', // 1% of 14px
  NAV_ACTIVE_WEIGHT: 600,
  NAV_INACTIVE_WEIGHT: 400,
  NAV_ACTIVE_COLOR: '#000000',
  NAV_INACTIVE_COLOR: '#256111',
  BUTTON_WIDTH: '138px',
  BUTTON_HEIGHT: '40px',
  BUTTON_BORDER_RADIUS: '12px',
  BUTTON_BORDER_WIDTH: '1px',
  BUTTON_PADDING: '8px 16px',
  BUTTON_GAP: '12px',
  QUESTIONER_BORDER_COLOR: '#256111',
  QUESTIONER_TEXT_COLOR: '#256111',
  BUTTON_FONT_FAMILY: 'Lexend, sans-serif',
  BUTTON_FONT_WEIGHT: 500,
  BUTTON_FONT_SIZE: '16px',
  BUTTON_LINE_HEIGHT: '24px',
  BUTTON_LETTER_SPACING: '0px', // 0% = 0px
} as const;

