// Signup Page Constants (using pixels)
export const SIGNUP_CONSTANTS = {
  CONTAINER_WIDTH: '600px',
  CONTAINER_PADDING: '40px 120px',
  CONTAINER_HEIGHT: '850px',
  CONTAINER_GAP: '8px',
  TITLE_MARGIN_TOP: '20px',
  TITLE_MARGIN_BOTTOM: '24px',
  FIELD_MARGIN_BOTTOM: '16px',
  LABEL_MARGIN_BOTTOM: '8px',
  BUTTON_MARGIN_TOP: '16px',
  OR_MARGIN_TOP: '24px',
  OR_MARGIN_BOTTOM: '24px',
  OR_PADDING: '0 12px',
  SOCIAL_BUTTONS_GAP: '16px',
  LOGIN_LINK_MARGIN_TOP: '24px',
  TERMS_PADDING_TOP: '16px',
  TERMS_TEXT_PADDING: '24px',
} as const;

