// Dashboard Page Constants (using pixels)
export const DASHBOARD_CONSTANTS = {
  // Success Banner (First Box)
  SUCCESS_BANNER_WIDTH: '100%',
  SUCCESS_BANNER_HEIGHT: '40px',
  SUCCESS_BANNER_PADDING: '8px 16px',
  SUCCESS_BANNER_BORDER_RADIUS: '12px',
  SUCCESS_BANNER_BACKGROUND_COLOR: '#E1FCDE',
  SUCCESS_BANNER_GAP: '12px',
  SUCCESS_BANNER_TOP: '20px',
  SUCCESS_BANNER_LEFT: '120px',

  // Success Banner Text
  SUCCESS_BANNER_TEXT_FONT_FAMILY: 'Lexend, sans-serif',
  SUCCESS_BANNER_TEXT_FONT_WEIGHT: 400,
  SUCCESS_BANNER_TEXT_FONT_SIZE: '14px',
  SUCCESS_BANNER_TEXT_LINE_HEIGHT: '20px',
  SUCCESS_BANNER_TEXT_LETTER_SPACING: '0%',
  SUCCESS_BANNER_TEXT_COLOR: '#1A212B',
  SUCCESS_BANNER_TEXT_WIDTH: '100%',

  // Success Banner Icon
  SUCCESS_BANNER_ICON_SIZE: '24px',
  SUCCESS_BANNER_CLOSE_ICON_SIZE: '10px',

  // Container
  CONTAINER_PADDING: '0 80px',
  CONTAINER_GAP: '20px',

  // Schedule Test Section
  SCHEDULE_SECTION_WIDTH: '100%',
  SCHEDULE_SECTION_HEIGHT: '160px',
  SCHEDULE_SECTION_BACKGROUND_COLOR: '#F7F7F7',
  SCHEDULE_SECTION_BORDER_RADIUS: '20px',
  SCHEDULE_SECTION_BORDER: '1px solid #E9E9E9',
  SCHEDULE_SECTION_PADDING: '30px 40px',
  SCHEDULE_SECTION_GAP: '20px',
  SCHEDULE_SECTION_MARGIN_TOP: '20px',
  SCHEDULE_SECTION_MARGIN_LEFT: '92px',

  // Schedule Test Title
  SCHEDULE_TITLE_FONT_FAMILY: 'Inter, sans-serif',
  SCHEDULE_TITLE_FONT_WEIGHT: 700,
  SCHEDULE_TITLE_FONT_SIZE: '24px',
  SCHEDULE_TITLE_LINE_HEIGHT: '32px',
  SCHEDULE_TITLE_COLOR: '#1A212B',
  SCHEDULE_TITLE_MARGIN_BOTTOM: '12px',

  // Schedule Test Description
  SCHEDULE_DESCRIPTION_FONT_FAMILY: 'Inter, sans-serif',
  SCHEDULE_DESCRIPTION_FONT_WEIGHT: 400,
  SCHEDULE_DESCRIPTION_FONT_SIZE: '14px',
  SCHEDULE_DESCRIPTION_LINE_HEIGHT: '20px',
  SCHEDULE_DESCRIPTION_COLOR: '#666666',
  SCHEDULE_DESCRIPTION_MARGIN_BOTTOM: '16px',

  // Schedule Button
  SCHEDULE_BUTTON_WIDTH: '200px',
  SCHEDULE_BUTTON_HEIGHT: '48px',
  SCHEDULE_BUTTON_BACKGROUND_COLOR: '#006045',
  SCHEDULE_BUTTON_TEXT_COLOR: '#FFFFFF',
  SCHEDULE_BUTTON_FONT_FAMILY: 'Inter, sans-serif',
  SCHEDULE_BUTTON_FONT_WEIGHT: 500,
  SCHEDULE_BUTTON_FONT_SIZE: '16px',
  SCHEDULE_BUTTON_BORDER_RADIUS: '8px',

  // Discover Section
  DISCOVER_SECTION_MARGIN_TOP: '20px',
  DISCOVER_SECTION_GAP: '20px',

  // Discover Title
  DISCOVER_TITLE_FONT_FAMILY: 'Inter, sans-serif',
  DISCOVER_TITLE_FONT_WEIGHT: 700,
  DISCOVER_TITLE_FONT_SIZE: '24px',
  DISCOVER_TITLE_LINE_HEIGHT: '32px',
  DISCOVER_TITLE_COLOR: '#1A212B',
  DISCOVER_TITLE_MARGIN_BOTTOM: '0px',

  // Discover Description
  DISCOVER_DESCRIPTION_FONT_FAMILY: 'Inter, sans-serif',
  DISCOVER_DESCRIPTION_FONT_WEIGHT: 400,
  DISCOVER_DESCRIPTION_FONT_SIZE: '14px',
  DISCOVER_DESCRIPTION_LINE_HEIGHT: '20px',
  DISCOVER_DESCRIPTION_COLOR: '#9095A1',
  DISCOVER_DESCRIPTION_MARGIN_BOTTOM: '16px',

  // Feature Cards
  FEATURE_CARDS_GAP: '32px',
  FEATURE_CARD_WIDTH: '290px',
  FEATURE_CARD_HEIGHT: '170px',
  FEATURE_CARD_BACKGROUND_COLOR: '#FFFFFF',
  FEATURE_CARD_BORDER_RADIUS: '24px',
  FEATURE_CARD_PADDING: '16px',
  // FEATURE_CARD_BOX_SHADOW: '0px 2px 12px 0px rgba(20, 20, 43, 0.08)',

  // Feature Card Icon
  FEATURE_CARD_ICON_SIZE: '35px',
  FEATURE_CARD_ICON_MARGIN_BOTTOM: '16px',

  // Feature Card Title
  FEATURE_CARD_TITLE_FONT_FAMILY: 'Inter, sans-serif',
  FEATURE_CARD_TITLE_FONT_WEIGHT: 600,
  FEATURE_CARD_TITLE_FONT_SIZE: '16px',
  FEATURE_CARD_TITLE_LINE_HEIGHT: '20px',
  FEATURE_CARD_TITLE_COLOR: '#1A212B',
  FEATURE_CARD_TITLE_MARGIN_BOTTOM: '4px',

  // Feature Card Description
  FEATURE_CARD_DESCRIPTION_FONT_FAMILY: 'Inter, sans-serif',
  FEATURE_CARD_DESCRIPTION_FONT_WEIGHT: 400,
  FEATURE_CARD_DESCRIPTION_FONT_SIZE: '12px',
  FEATURE_CARD_DESCRIPTION_LINE_HEIGHT: '18px',
  FEATURE_CARD_DESCRIPTION_COLOR: '#9095A1',
} as const;

